### ISSUE TITLE
Is it expected to have the value of a weighted index to be 1 as the number of fingerprints becomes larger?

### ISSUE THREAD

**Issue by yipy0005** [ramirandaq/MultipleComparisons#2]
Hi!

I was using the MultiComp.py in the condensed_version folder on a set of 50000 fingerprints. I then proceeded to obtain the value of the weighted and non-weighted JT indices and I found that the weighted JT index is 1.0. I tried with different sets of 50000 fingerprints and the weighted JT index value is always 1.0.

I'm still trying to wrap my head around after studying the article. But I would like to ask if this is expected behaviour and what could be a possible reason(s) for such a behaviour?

Thank you!
Yew Mun

**Comment by ramirandaq** [comment]
Hi, thanks for getting in touch! Indeed, it is to be expected that the weighted indices give values that are very close to 1 (if not even exactly 1, as in your case) for libraries that are not very diverse. In practice, all the work that we have done has been using non_weighted indices. Another possible way around this issue is to perform the calculations with larger coincidence thresholds. For N molecules, the coincidence threshold could be between Nmod2 and N-1. The default in the package is Nmod2, which is guaranteed to give the highest possible similarity values, so picking a higher value for this hyperparameter will give extended similarity values different from 1. Still, the preferred solution would be to use only non-weighted indices. We'll be happy to talk more if you need more assistance. All the best,
Ramon

**Comment by yipy0005** [comment]
Thanks Ramon! Your answer has been a great help to me towards understanding how ESIs work. 👍🏻
